### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by OlesiaSemen**

### CODE REVIEW

**Review by Ivan-Shvorak — CHANGES_REQUESTED** [review]
Tests are failed, please make sure that all auto-checks are passed

**Review by Ivan-Shvorak — CHANGES_REQUESTED** [review]
Checks still are failed, please make sure that all auto-checks are passed before sending task to review

**Review by 4ksandrey — CHANGES_REQUESTED** [review]
Not fixed, run npm test before sending task on review, all tests should be passed, revise it and fix

**Comment by PolinaRomanenko** [comment]
well, this is yet not fixed

**Review by PolinaRomanenko — CHANGES_REQUESTED** [review]
I contacted you is Slack, please, look at the comment and check your  auto-tests)

**Pull request closed without merging**
