### PR TITLE
task clones

### PR DESCRIPTION
**Pull request by SerhiiSemennikov**
first attempt

### CODE REVIEW

**Review by SerhiiSemennikov — COMMENTED** [review]
with changes 1

**Review by SerhiiSemennikov — COMMENTED** [review]
finish

**Review by SerhiiSemennikov — COMMENTED** [review]
1

**Review by SerhiiSemennikov — COMMENTED** [review]
2

**Review by SerhiiSemennikov — COMMENTED** [review]
3

**Review by SerhiiSemennikov — COMMENTED** [review]
add default

**Review by TarasHoliuk — APPROVED** [review]

**Pull request closed without merging**
